version: "3.4"
services:
  mongo:
        image: 'mongo:4.4'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
           MONGODB_URI: mongodb://localhost:27017